'use strict';

/*
 Each new term in the Fibonacci sequence is generated by adding the previous two
 terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed
 four million, find the sum of the even-valued terms.
 */

function fibonacci(n) {
  if (n === 1 || n === 2) {
    return 1;
  }
  return fibonacci(n - 1) + fibonacci(n - 2);
}

let sum = 0;
let n;
for (let n = 1;; ++n) {
  let current = fibonacci(n);
  if (current >= 4000000) {
    break;
  }
  if (current % 2 === 0) {
    sum += current;
  }
}

console.log(sum, sum === 4613732);
